### ISSUE TITLE
Disable blur effect without disabling OpenGL acceleration

### ISSUE THREAD

**Issue by jclc** [naelstrof/slop#67]
I noticed that there's been added a blur effect for the duration of the selection, rather problematic since it even shows up in screenshots taken with maim. Disabling OpenGL acceleration does disable it, but it also creates that selection box artifact that plagues scrot. I didn't find an option to disable it in the man page, did I miss something?

**Comment by naelstrof** [comment]
Try increasing the --bordersize, and disabling OpenGL for now. I believe I know what's wrong (linear sampling on the texture) and it should be fixed in the next patch.

**Comment by naelstrof** [comment]
Should be fixed in https://github.com/naelstrof/slop/releases/tag/v5.3.36

Could you test it out for me?

**Comment by naelstrof** [comment]
If it's not fixed, please post an image of the problem. Not sure what kind of blur effect we're talking about here.

**Comment by jclc** [comment]
After compiling the latest releases for slop and maim, the screenshots taken are no longer blurry! The blur effect still doesn't seem to work as intended (I'm assuming the selection is meant to be unblurred?), but the issue is fixed. I will continue experimenting with these new shaders though, they do seem interesting

**Comment by naelstrof** [comment]
blur1 is a shader that reads pixels off the desktop, blurs them horizontally, then multiplies it by the current selection rectangle.
blur2 is a shader that only blurs the selection rectangle vertically.

Together you'll get a full guassian blur in both the x and the y direction. I realize the horizontal alpha might be a bit messed up since it doesn't blur the selection rectangle for alpha, but it should be accurate enough for most.

**Comment by naelstrof** [comment]
I'm going to close this issue though, feel free to ask questions about shaders in another thread.

**Comment by jclc** [comment]
Alright. However, I just realised that I might have worded the issue badly, so I wanted to specify that the entire screen is being blurred, not just the box around the selection.
